name: OSX build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build OSX version
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: 
          ./tools/buildOSX.sh
          
      - uses: actions/upload-artifact@v4
        with:
          name: OSXBinaries
          path: ./libbulletc/libbulletc-OSX/build/Release
          
