name: Unix build
on:
  push:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./tools/build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: UnixBinaries
          path: ./build